# Generated by Django 6.0.8 on 2026-08-26 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('command', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('running', 'Running'), ('ok', 'Completed'), ('error', 'Failed')], default='running', max_length=10)),
                ('summary', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'job run',
                'verbose_name_plural': 'job runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['command', '-started_at'], name='core_jobrun_command_9e33ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('rol', models.CharField(choices=[('miembro', 'Member'), ('admin', 'Admin')], default='miembro', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('nombre', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('miembros', models.ManyToManyField(related_name='organizaciones', through='core.Membresia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='membresia',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveBigIntegerField(default=0, editable=False)),
                ('action', models.CharField(max_length=32)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('model_label', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-sequence'],
                'indexes': [models.Index(fields=['-sequence'], name='core_audite_sequenc_5b095b_idx'), models.Index(fields=['actor', '-sequence'], name='core_audite_actor_i_b9b9dd_idx'), models.Index(fields=['model_label', 'object_id'], name='core_audite_model_l_6c8dda_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('organizacion', 'usuario'), name='unica_membresia_por_organizacion'),
        ),
    ]
