# Generated by Django 6.0.8 on 2026-09-21 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tabla_de_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('tipo', models.CharField(choices=[('asignacion', 'Assigned to you'), ('comentario', 'New reply'), ('vencimiento', 'Overdue'), ('transmittal', 'Documents issued')], max_length=20)),
                ('titulo', models.CharField(max_length=250, verbose_name='title')),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('proyecto', models.CharField(blank=True, max_length=60)),
                ('objeto', models.CharField(blank=True, max_length=80)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('de_parte_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_provocados', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario', 'leido_en'], name='core_aviso_destina_d51b3c_idx')],
            },
        ),
    ]
