# Generated by Django 6.0.8 on 2026-09-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Assigned to you'), ('comentario', 'New reply'), ('vencimiento', 'Overdue'), ('transmittal', 'Documents issued'), ('interferencias', 'Clash review')], max_length=20),
        ),
    ]
