# Generated by Django 6.0.8 on 2026-08-26 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('codigo', models.CharField(max_length=80, verbose_name='code')),
                ('titulo', models.CharField(max_length=250, verbose_name='title')),
                ('tipo', models.CharField(choices=[('plano', 'Drawing'), ('memoria', 'Report'), ('modelo', 'Model'), ('especificacion', 'Specification'), ('otro', 'Other')], default='plano', max_length=20)),
                ('fecha_planificada', models.DateField(blank=True, null=True, verbose_name='planned date')),
                ('peso', models.PositiveIntegerField(default=1, verbose_name='weight')),
            ],
            options={
                'verbose_name': 'deliverable',
                'verbose_name_plural': 'deliverables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('titulo', models.CharField(max_length=250, verbose_name='title')),
                ('descripcion', models.TextField(blank=True, verbose_name='description')),
                ('prioridad', models.CharField(choices=[('alta', 'High'), ('media', 'Medium'), ('baja', 'Low')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierta', 'Open'), ('respondida', 'Answered'), ('cerrada', 'Closed'), ('descartada', 'Dismissed')], default='abierta', max_length=20)),
                ('vence', models.DateField(blank=True, null=True, verbose_name='due')),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, verbose_name='resolution')),
                ('pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('ancla_x', models.FloatField(blank=True, null=True)),
                ('ancla_y', models.FloatField(blank=True, null=True)),
                ('ifc_guid', models.CharField(blank=True, db_index=True, max_length=22)),
                ('punto_de_vista', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('correlativo', models.CharField(max_length=20, verbose_name='revision')),
                ('idoneidad', models.CharField(choices=[('S0', 'S0 · Work in progress'), ('S1', 'S1 · Suitable for coordination'), ('S2', 'S2 · Suitable for information'), ('S3', 'S3 · Suitable for review and comment'), ('S4', 'S4 · Suitable for stage approval'), ('S6', 'S6 · Suitable for PIM authorisation'), ('S7', 'S7 · Suitable for AIM authorisation'), ('A', 'A · Published and authorised'), ('B', 'B · Published with comments')], default='S0', max_length=2, verbose_name='suitability')),
                ('clave_archivo', models.CharField(blank=True, max_length=400)),
                ('nombre_original', models.CharField(blank=True, max_length=250)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('emitida_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='issued')),
                ('es_vigente', models.BooleanField(default=True, verbose_name='current')),
            ],
            options={
                'verbose_name': 'revision',
                'verbose_name_plural': 'revisions',
                'ordering': ['-emitida_en'],
            },
        ),
        migrations.CreateModel(
            name='Transmittal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('folio', models.CharField(max_length=40, verbose_name='reference')),
                ('asunto', models.CharField(max_length=250, verbose_name='subject')),
                ('status', models.CharField(choices=[('borrador', 'Draft'), ('emitido', 'Issued'), ('acusado', 'Acknowledged'), ('anulado', 'Cancelled')], default='borrador', max_length=20)),
                ('emitido_en', models.DateTimeField(blank=True, null=True)),
                ('acusado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'transmittal',
                'verbose_name_plural': 'transmittals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('titulo', models.CharField(max_length=250, verbose_name='title')),
                ('descripcion', models.TextField(blank=True, verbose_name='description')),
                ('vence', models.DateField(blank=True, null=True, verbose_name='due')),
                ('status', models.CharField(choices=[('pendiente', 'Pending'), ('en_curso', 'In progress'), ('en_revision', 'Under review'), ('hecha', 'Done'), ('anulada', 'Cancelled')], default='pendiente', max_length=20)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['vence', '-created_at'],
            },
        ),
    ]
