# Generated by Django 6.0.8 on 2026-08-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregable',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables', to='projects.disciplina'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregables', to='projects.paquetewbs'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregables_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='entregable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='documents.entregable'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_abiertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacion',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='observacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='documents.observacion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='documents.observacion'),
        ),
        migrations.AddField(
            model_name='revision',
            name='entregable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='documents.entregable'),
        ),
        migrations.AddField(
            model_name='revision',
            name='subida_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_subidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacion',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='documents.revision'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='transmittals_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmittals_emitidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmittals', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmittals', to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='transmittal',
            name='revisiones',
            field=models.ManyToManyField(blank=True, related_name='transmittals', to='documents.revision'),
        ),
        migrations.AddIndex(
            model_name='entregable',
            index=models.Index(fields=['proyecto', 'disciplina'], name='documents_e_proyect_dfb3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='entregable',
            index=models.Index(fields=['responsable'], name='documents_e_respons_6569a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='entregable',
            constraint=models.UniqueConstraint(fields=('proyecto', 'codigo'), name='codigo_de_entregable_unico_por_proyecto'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['responsable', 'status'], name='documents_a_respons_488d23_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['proyecto', 'status'], name='documents_a_proyect_e7f922_idx'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['entregable', '-emitida_en'], name='documents_r_entrega_9bf9bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('entregable', 'correlativo'), name='correlativo_de_revision_unico_por_entregable'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['responsable', 'estado'], name='documents_o_respons_ebf68e_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['proyecto', 'estado'], name='documents_o_proyect_0e8b3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='transmittal',
            constraint=models.UniqueConstraint(fields=('proyecto', 'folio'), name='folio_de_transmittal_unico_por_proyecto'),
        ),
    ]
