# Generated by Django 6.0.8 on 2026-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='metadatos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
