# Generated by Django 6.0.8 on 2026-08-26 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0003_revision_metadatos'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoIds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('titulo', models.CharField(max_length=250, verbose_name='title')),
                ('clave_archivo', models.CharField(blank=True, max_length=400)),
                ('nombre_original', models.CharField(blank=True, max_length=250)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_ids', to='core.organizacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_ids', to='projects.proyecto')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitos_ids_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'information requirement',
                'verbose_name_plural': 'information requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionIds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('cumple', models.BooleanField(default=False, verbose_name='complies')),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('corrida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_ids', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_ids', to='core.organizacion')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='documents.requisitoids')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='documents.revision')),
            ],
            options={
                'verbose_name': 'IDS validation',
                'verbose_name_plural': 'IDS validations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['revision', '-created_at'], name='documents_v_revisio_52db30_idx')],
            },
        ),
    ]
