# Generated by Django 6.0.8 on 2026-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_requisitoids_validacionids'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='visibilidad',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
