# Generated by Django 6.0.8 on 2026-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_observacion_visibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='instantanea',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
