# Generated by Django 6.0.8 on 2026-09-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_observacion_instantanea'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='marcado',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
