# Generated by Django 6.0.8 on 2026-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_observacion_marcado'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='interferencia_con',
            field=models.CharField(blank=True, db_index=True, max_length=22),
        ),
    ]
