# Generated by Django 6.0.8 on 2026-09-02 17:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0008_observacion_interferencia_con'),
        ('projects', '0002_vistadeproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaDeCoordinacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('visto_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='seen up to')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_de_coordinacion', to='core.organizacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_de_coordinacion', to='projects.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_de_coordinacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coordination mark',
                'verbose_name_plural': 'coordination marks',
                'ordering': ['-visto_en'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'usuario'), name='marca_unica_por_persona_y_obra')],
            },
        ),
    ]
