# Generated by Django 6.0.8 on 2026-09-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_marcadecoordinacion'),
        ('projects', '0003_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='observaciones', to='projects.etiqueta', verbose_name='tags'),
        ),
    ]
