# Generated by Django 6.0.8 on 2026-09-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_observacion_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='clave_dxf',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='revision',
            name='motivo_sin_dxf',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
