# Generated by Django 6.0.8 on 2026-09-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_revision_clave_dxf_revision_motivo_sin_dxf"),
    ]

    operations = [
        migrations.AddField(
            model_name="observacion",
            name="ancla_nube_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observacion",
            name="ancla_nube_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observacion",
            name="ancla_nube_z",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
