# Generated by Django 6.0.8 on 2026-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0012_observacion_ancla_nube_x_observacion_ancla_nube_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="imagen",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
