# Generated by Django 6.0.8 on 2026-09-14 21:38

import apps.documents.compartir
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_comentario_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceCompartido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('testigo', models.CharField(db_index=True, default=apps.documents.compartir.nuevo_testigo, editable=False, max_length=64, unique=True)),
                ('para', models.CharField(help_text='A name you will recognise later, to revoke this one and not the others.', max_length=150, verbose_name='who it is for')),
                ('expira_en', models.DateTimeField(verbose_name='expires')),
                ('revocado_en', models.DateTimeField(blank=True, null=True, verbose_name='revoked')),
                ('visitas', models.PositiveIntegerField(default=0, editable=False)),
                ('ultima_visita', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_compartidos', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_compartidos', to='documents.revision', verbose_name='revision')),
            ],
            options={
                'verbose_name': 'shared link',
                'verbose_name_plural': 'shared links',
                'ordering': ['-created_at'],
            },
        ),
    ]
