# Generated by Django 6.0.8 on 2026-09-23 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_enlacecompartido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'digest sent',
                'verbose_name_plural': 'digests sent',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='un_resumen_por_persona_y_dia')],
            },
        ),
    ]
