# Generated by Django 6.0.8 on 2026-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_resumenenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='ancla_forma',
            field=models.CharField(blank=True, choices=[('rectangulo', 'Rectangle'), ('nube', 'Revision cloud'), ('llamada', 'Callout')], max_length=10),
        ),
        migrations.AddField(
            model_name='observacion',
            name='ancla_x2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='ancla_y2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
