# Generated by Django 6.0.8 on 2026-08-26 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('codigo', models.CharField(max_length=30, verbose_name='code')),
                ('nombre', models.CharField(max_length=200, verbose_name='name')),
                ('cliente', models.CharField(blank=True, max_length=200, verbose_name='client')),
                ('status', models.CharField(choices=[('anteproyecto', 'Concept'), ('basico', 'Scheme design'), ('detalle', 'Detailed design'), ('construccion', 'Construction'), ('cerrado', 'Closed')], default='anteproyecto', max_length=20)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='start')),
                ('termino', models.DateField(blank=True, null=True, verbose_name='end')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteWBS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('codigo', models.CharField(max_length=40, verbose_name='code')),
                ('nombre', models.CharField(max_length=200, verbose_name='name')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='projects.paquetewbs')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'WBS package',
                'verbose_name_plural': 'WBS packages',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('codigo', models.CharField(max_length=10, verbose_name='code')),
                ('nombre', models.CharField(max_length=100, verbose_name='name')),
                ('color', models.CharField(default='#5b3a9e', max_length=7, verbose_name='colour')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'discipline',
                'verbose_name_plural': 'disciplines',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('organizacion', 'codigo'), name='codigo_de_proyecto_unico_por_organizacion'),
        ),
        migrations.AddConstraint(
            model_name='paquetewbs',
            constraint=models.UniqueConstraint(fields=('proyecto', 'codigo'), name='codigo_de_paquete_unico_por_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('proyecto', 'codigo'), name='codigo_de_disciplina_unico_por_proyecto'),
        ),
    ]
