# Generated by Django 6.0.8 on 2026-08-28 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaDeProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('nombre', models.CharField(max_length=120, verbose_name='name')),
                ('camara', models.JSONField(blank=True, default=dict)),
                ('visibilidad', models.JSONField(blank=True, default=dict)),
                ('cortes', models.JSONField(blank=True, default=list)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vistas_compartidas', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vistas_de_proyecto', to='core.organizacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'project view',
                'verbose_name_plural': 'project views',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'nombre'), name='nombre_de_vista_unico_por_proyecto')],
            },
        ),
    ]
