# Generated by Django 6.0.8 on 2026-09-02 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_vistadeproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('nombre', models.CharField(max_length=60, verbose_name='name')),
                ('color', models.CharField(default='#5b3a9e', max_length=7, verbose_name='colour')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'nombre'), name='nombre_de_etiqueta_unico_por_proyecto')],
            },
        ),
    ]
