# Generated by Django 6.0.8 on 2026-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='naturaleza',
            field=models.CharField(choices=[('real', 'Live work'), ('prueba', 'Test'), ('demo', 'Demo')], default='real', max_length=10, verbose_name='nature'),
        ),
    ]
