# Generated by Django 6.0.8 on 2026-09-21 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_proyecto_naturaleza'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisosDeObra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('resumen', models.CharField(choices=[('solo_vencidos', 'Only when something is overdue'), ('diario', 'Every day'), ('semanal', 'Once a week'), ('nunca', 'Never')], default='solo_vencidos', max_length=20, verbose_name='summary email')),
                ('dia_de_la_semana', models.PositiveSmallIntegerField(default=0)),
                ('al_asignar', models.BooleanField(default=True, verbose_name='email when work is assigned')),
                ('al_responder', models.BooleanField(default=True, verbose_name='email on every reply in a thread')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_de_aviso', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'notice settings',
                'verbose_name_plural': 'notice settings',
            },
        ),
    ]
